class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.ZipMirrorCommand = 'zipmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'list3'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users3'
        self.AuthorizeCommand = 'authorize3'
        self.UnAuthorizeCommand = 'unauthorize3'
        self.AddSudoCommand = 'addsudo3'
        self.RmSudoCommand = 'rmsudo3'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone3'
        self.CountCommand = 'count3'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.ZipWatchCommand = 'zipwatch3'
        self.QbMirrorCommand = 'qbmirror3'
        self.QbUnzipMirrorCommand = 'qbunzipmirror3'
        self.QbTarMirrorCommand = 'qbtarmirror3'
        self.QbZipMirrorCommand = 'qbzipmirror3'
        self.DeleteCommand = 'del3'
        self.ShellCommand = 'shell3'
        self.ExecHelpCommand = 'exechelp3'
        self.TsHelpCommand = 'tshelp3'

BotCommands = _BotCommands()
